spring.application.name=virtual-plc-simulator
server.port=9090

mes-server.base-url=http://localhost:8080

mes-server.api-key=${PLC_API_KEY:local-plc-api-key}
mes-server.hmac-secret-key=${PLC_HMAC_SECRET_KEY:local-hmac-secret-key}