spring.application.name=mes-server

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1

spring.datasource.username=${DB_USERNAME:mes_user}
spring.datasource.password=${DB_PASSWORD:mes1234}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

server.port=8080

plc.api-key=${PLC_API_KEY:local-plc-api-key}
plc.hmac-secret-key=${PLC_HMAC_SECRET_KEY:local-hmac-secret-key}

plc.timestamp-valid-seconds=300
